# Change these first
owner: einvasion-id # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: E-Invasion
    url: https://e-invasion.com
  - name: Babyplan.com
    url: https://babyplan.com
  - name: Babyplan.dk
    url: https://babyplan.dk
  - name: Babyplan.se
    url: https://babyplan.se
  - name: Babyplan.no
    url: https://babyplan.no
  - name: Billige-Teste.dk
    url: https://billige-teste.dk
  - name: Billiga-Tester.se
    url: https://billiga-tester.se
  - name: Billige-Tester.no
    url: https://billige-tester.no
  - name: Clearblueshop.dk
    url: https://clearblueshop.dk
  - name: Clearblueshop.se
    url: https://clearblueshop.se
  - name: Clearblueshop.no
    url: https://clearblueshop.no
  - name: Swimcount.se
    url: https://swimcount.se

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
